app:
  image:
    repository: denisviskov/passport-service
    tag: latest
    pullPolicy: Always
  replicas: 2
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
    requests:
      cpu: "200m"
      memory: "512Mi"
  service:
    port: 80
    targetPort: 9090
    type: ClusterIP