apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.app.db.host }}:{{ .Values.app.db.port }}/{{ .Values.app.db.name }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.app.db.username }}"