apiVersion: v1
kind: Service
metadata:
  name: passport-app
spec:
  selector:
    app: passport-app
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
  type: {{ .Values.app.service.type }}