server:
  port: 9090

spring:

  jpa:
      hibernate:
        ddl-auto: validate
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

  datasource:
      url: jdbc:postgresql://localhost:5432/passport
      username: "postgres"
      password: "021292"

  flyway:
      enabled: true
      validate-on-migrate: true

  restAPI:
      root: /passports
      save: ${spring.restAPI.root}/save
      update: ${spring.restAPI.root}/update
      delete: ${spring.restAPI.root}/delete
      find: ${spring.restAPI.root}/find
      findBySerial: ${spring.restAPI.find}
      unavailable: ${spring.restAPI.root}/unavailable
      findReplaceable: ${spring.restAPI.root}/find-replaceable