volumes:
  data:

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: passport
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 021292
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
      - ./db_scripts:/docker-entrypoint-initdb.d
