# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: passport-app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/passport"
  SPRING_DATASOURCE_USERNAME: "postgres"
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passport-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: passport-app
  template:
    metadata:
      labels:
        app: passport-app
    spec:
      containers:
        - name: passport-service
          image: denisviskov/passport-service:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: passport-app-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: passport-app-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          readinessProbe:
            httpGet:
              path: /actuator/health  # Замени, если Actuator не включен
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
---
# Service для приложения
apiVersion: v1
kind: Service
metadata:
  name: passport-app
spec:
  selector:
    app: passport-app
  ports:
    - port: 80
      targetPort: 9090
  type: ClusterIP