global:
  namespace: default

passport-service-app:
  enabled: true
  # Параметры для passport-service-app (пока можно оставить дефолтные из subchart)

postgres:
  enabled: true
  # Параметры для postgres (пока можно оставить дефолтные из subchart)