POST localhost:9090/passports/save
Content-Type: application/json

{
  "id": "",
  "serial_number": 2230,
  "main_number": 188235,
  "name": "John",
  "surname": "Garret",
  "birth_date": "02.12.1992",
  "issuing_authority": "Test issuing authority",
  "date_of_issue": "30.01.2022",
  "expired_date": "30.01.2033"
}