apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - {{ .Values.postgres.storage.accessModes }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}